dashboard_access_code = "Mila2026"
google_sheet_id = "1OFIEM0Ib-tNDk2Wr2o5Zvz8C8jKetVJi1UFPv4faE3k"

[gcp_service_account]
type = "service_account"
project_id = "bachelor-thesis-496211"
private_key_id = "58c276fb2d221c645ebff6f7030a757a961e7d59"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDKZ9o/E7lP9BCN
rLfc7JL72xalwJWfFX4aP37Q5zRmH3z3WCP68pSriAHJaU38RCzIlQe0R5eGIZpw
iUMsM4RhI6DkbYvqKiovMBD8TG3oVllyCpZAwSNVqRAX+8rrjV0Kfhu4tWuUjBpu
4sdIL1CbHJS7cg+8XIrg7p5ac5dSnjA27zh5kB+PgKwg2TdO+bzGf3pJOeCReGcO
zqfJZAtGHbUh9nlt5BucaPNKzwnvy9AMMG03pgTQGzQAnNkNBS0bomKlTfz6iV9V
rseML/G4fQBbKQ8gjKsC6gZHq+qfoxbYGVnEJXE95aooPYgQ6YpVnZXvQvALQhib
bgtoI5kNAgMBAAECggEAVEhujvmNnweIpRYY8fvpMMsIYTkSlM4EVrW9/wtnvGa8
SNsBEIxW8B6Qb+hTuwpAg73bGWz+YbI4d0gRGqTRKQoHA1fCfV3VdxTS3dyNn8Pl
NyHFc215Y0AlHXeSBgg1iBr/PCj/hTnZ//aa+SoKrKx4Gp3ig5MdmZCDjDK5/oJ2
Zx4ZgeNg9atcDHS7b7glsnSKVLEirhRBLuOa/eoGC3sNLKydkyAlD7Fjy6NJqByT
qkRCSphpIjgu4HNUe3piMXhDJvUp21PU1p1HX/JzYJIJgPbv6D43HVzlNW8w9km4
D+F1IOffEeUBz7zwynSgT5iO/D184WtEbUcI1qR2mQKBgQD3CfWlqRiDbkvIP3aA
ZYhtMkRmHJ1UXs51zLuLiw2Aaj+oCplfAFsuR7/dRYZsGkuhRVKj54whIS0rddvS
9X1vgBnI847GCcwBZSrlD/isyn3bx91bAySyMQBM5e4Ypu/wojuVLccjvhjDe7HF
ZQbI1fm0FhLJpu/61w4m6u5dewKBgQDRv2wMzSgqe1VoCa2JQtN56wARESsj/EP/
5mrlciD/ZBCzbtASMatyRp9o78XbGIOxdg++LelDIrtd/pXTgOLspNXCqGtmSijj
JEIWoWvmxm8qs3Leis2SPH8nW7vr7GeX9wBMXE+hqlAosEW83G1W6aco9y7mtP5d
2eFYcBmpFwKBgQDtmpy0O1GiiCFHdxLJJ97x+BklhXwlPBKj5sizzIit7INRYvBl
GXiZqNT3Q/moXBpGAOEdWIXFD53cYT2PSCLfbXxfdTLrc1zOMrnxG015FEG9dByJ
fxp6cPry+2voNhgtgDyCnUceL6atznkLfMHrxTKobVqgrXm/77xi3i9ppQKBgBjB
ZghQwnfZHKht0/yKVZljIhvhkdzqbkAqut0fzkM2VT5ISuiK0jhnm3LwMcL9LrXo
QE1q78gLtl+Op7JR2PajMdOKuzpUcGT2p5IyNSEEtKQuj9UyPrcOytcjXZenzEZE
UdWxY3iqOFHFFEYJIiKK6z7Lhc6W+Bqtl4ovmOe7AoGAe0on1Qh0zt9TkW6tpVmZ
vdSmm59yuUQExZlQTX4gTV6miwxpkLyr4p6yttRdl/I93yayQ8GkncJDeU/+sjNO
qV27/5ZVSJ1gAF0805L7/ODi8MG4kQA2FkbgirCV9SAdYDZObVZFKvMe6dBgjR4c
nomLKLMqUVY5a6YU7Etrs4g=
-----END PRIVATE KEY-----"""
client_email = "streamlit-thesis-dashboard@bachelor-thesis-496211.iam.gserviceaccount.com"
client_id = "109429757090719048883"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-thesis-dashboard%40bachelor-thesis-496211.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
